tab_bar_align center
tab_bar_style powerline
tab_bar_align left
tab_powerline_style angled
tab_activity_symbol "󱐋 "
tab_bar_edge top
#tab_bar_background #1d1d2c
tab_bar_min_tabs 1
#tab_activity_symbol ❗
tab_title_template "{fmt.fg._f9e2ae}{bell_symbol}{activity_symbol}{fmt.fg.default}{tab.progress_percent}{fmt.fg.tab}{index}:{'🇿' if layout_name == 'stack' and num_windows > 1 else ''}{title}"
